FROM node:20.15.0-alpine3.20
WORKDIR /usr/src/app

ARG DB_HOST
ARG DB_PASS
ARG DB_PORT
ARG DATABASE
ARG INFLUX_URL
ARG INFLUXDB_TOKEN
ARG INFLUX_ORG
ARG INFLUX_BUCKET
ARG SECRET

ENV DB_HOST=$DB_HOST
ENV DB_PASS=$DB_PASS
ENV DB_PORT=$DB_PORT
ENV DATABASE=$DATABASE
ENV INFLUX_URL=$INFLUX_URL
ENV INFLUXDB_TOKEN=$INFLUXDB_TOKEN
ENV INFLUX_ORG=$INFLUX_ORG
ENV INFLUX_BUCKET=$INFLUX_BUCKET
ENV SECRET=$SECRET

COPY package*.json ./
RUN npm install
COPY . .

EXPOSE 4000
CMD [ "node", "index.js"]